DO $pdd_data$
BEGIN
-- Data for Name: business_areas; Type: TABLE DATA; Schema: public; Owner: postgres
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (1, 'General');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (2, 'Enterprise');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (3, 'Fintech');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (4, 'Mobility');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (5, 'Insurtech');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (6, 'Big Data');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (7, 'Healthcare');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (8, 'Manufacturing');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (9, 'Hardware');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (10, 'Proptech');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (11, 'AI');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (12, 'Edtech');
INSERT INTO public.business_areas OVERRIDING SYSTEM VALUE VALUES (13, 'Consumer');
-- Data for Name: business_role_types; Type: TABLE DATA; Schema: public; Owner: postgres
INSERT INTO public.business_role_types OVERRIDING SYSTEM VALUE VALUES (1, 'Managerial');
INSERT INTO public.business_role_types OVERRIDING SYSTEM VALUE VALUES (2, 'Design');
INSERT INTO public.business_role_types OVERRIDING SYSTEM VALUE VALUES (3, 'Development');
INSERT INTO public.business_role_types OVERRIDING SYSTEM VALUE VALUES (4, 'Devops');
INSERT INTO public.business_role_types OVERRIDING SYSTEM VALUE VALUES (5, 'QA');
INSERT INTO public.business_role_types OVERRIDING SYSTEM VALUE VALUES (6, 'Database');
-- Data for Name: business_roles; Type: TABLE DATA; Schema: public; Owner: postgres
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (1, 'Product Owner', 1);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (2, 'Project Manager', 1);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (3, 'UX Designer', 2);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (4, 'UI Designer', 2);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (5, 'Business Analyst', 1);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (6, 'Software Developer', 3);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (7, 'Software Architect', 3);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (8, 'Devops', 4);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (9, 'Devops Engineer', 4);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (10, 'Devops Lead', 4);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (11, 'Tester', 5);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (12, 'QA Lead', 5);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (13, 'QA Engineer', 5);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (14, 'Tech lead', 1);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (15, 'Scrum master', 1);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (16, 'Software Development Manager', 1);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (17, 'Database Administrator', 6);
INSERT INTO public.business_roles OVERRIDING SYSTEM VALUE VALUES (18, 'Database Developer', 6);
-- Data for Name: countries; Type: TABLE DATA; Schema: public; Owner: postgres
INSERT INTO public.countries VALUES (474, 'MQ', 'MTQ', 'Martinique', NULL);
INSERT INTO public.countries VALUES (478, 'MR', 'MRT', 'Mauritania', NULL);
INSERT INTO public.countries VALUES (480, 'MU', 'MUS', 'Mauritius', NULL);
INSERT INTO public.countries VALUES (175, 'YT', 'MYT', 'Mayotte', NULL);
INSERT INTO public.countries VALUES (484, 'MX', 'MEX', 'Mexico', 'es-MX');
INSERT INTO public.countries VALUES (583, 'FM', 'FSM', 'Micronesia, Federated States of', NULL);
INSERT INTO public.countries VALUES (498, 'MD', 'MDA', 'Moldova, Republic of', NULL);
INSERT INTO public.countries VALUES (492, 'MC', 'MCO', 'Monaco', 'fr-MC');
INSERT INTO public.countries VALUES (496, 'MN', 'MNG', 'Mongolia', 'mn');
INSERT INTO public.countries VALUES (500, 'MS', 'MSR', 'Montserrat', NULL);
INSERT INTO public.countries VALUES (504, 'MA', 'MAR', 'Morocco', 'ar-MA');
INSERT INTO public.countries VALUES (508, 'MZ', 'MOZ', 'Mozambique', NULL);
INSERT INTO public.countries VALUES (104, 'MM', 'MMR', 'Myanmar', NULL);
INSERT INTO public.countries VALUES (516, 'NA', 'NAM', 'Namibia', NULL);
INSERT INTO public.countries VALUES (520, 'NR', 'NRU', 'Nauru', NULL);
INSERT INTO public.countries VALUES (524, 'NP', 'NPL', 'Nepal', NULL);
INSERT INTO public.countries VALUES (528, 'NL', 'NLD', 'Netherlands', 'nl-NL');
INSERT INTO public.countries VALUES (530, 'AN', 'ANT', 'Netherlands Antilles', NULL);
INSERT INTO public.countries VALUES (540, 'NC', 'NCL', 'New Caledonia', NULL);
INSERT INTO public.countries VALUES (554, 'NZ', 'NZL', 'New Zealand', 'en-NZ');
INSERT INTO public.countries VALUES (558, 'NI', 'NIC', 'Nicaragua', 'es-NI');
INSERT INTO public.countries VALUES (562, 'NE', 'NER', 'Niger', NULL);
INSERT INTO public.countries VALUES (566, 'NG', 'NGA', 'Nigeria', NULL);
INSERT INTO public.countries VALUES (570, 'NU', 'NIU', 'Niue', NULL);
INSERT INTO public.countries VALUES (574, 'NF', 'NFK', 'Norfolk Island', NULL);
INSERT INTO public.countries VALUES (580, 'MP', 'MNP', 'Northern Mariana Islands', NULL);
INSERT INTO public.countries VALUES (578, 'NO', 'NOR', 'Norway', 'nb-NO');
INSERT INTO public.countries VALUES (512, 'OM', 'OMN', 'Oman', 'ar-OM');
INSERT INTO public.countries VALUES (586, 'PK', 'PAK', 'Pakistan', 'ur-PK');
INSERT INTO public.countries VALUES (585, 'PW', 'PLW', 'Palau', NULL);
INSERT INTO public.countries VALUES (591, 'PA', 'PAN', 'Panama', 'es-PA');
INSERT INTO public.countries VALUES (598, 'PG', 'PNG', 'Papua New Guinea', NULL);
INSERT INTO public.countries VALUES (600, 'PY', 'PRY', 'Paraguay', 'es-PY');
INSERT INTO public.countries VALUES (604, 'PE', 'PER', 'Peru', 'es-PE');
INSERT INTO public.countries VALUES (608, 'PH', 'PHL', 'Philippines', 'en-PH');
INSERT INTO public.countries VALUES (612, 'PN', 'PCN', 'Pitcairn', NULL);
INSERT INTO public.countries VALUES (616, 'PL', 'POL', 'Poland', 'pl-PL');
INSERT INTO public.countries VALUES (620, 'PT', 'PRT', 'Portugal', 'pt-PT');
INSERT INTO public.countries VALUES (630, 'PR', 'PRI', 'Puerto Rico', 'es-PR');
INSERT INTO public.countries VALUES (634, 'QA', 'QAT', 'Qatar', 'ar-QA');
INSERT INTO public.countries VALUES (638, 'RE', 'REU', 'Reunion', NULL);
INSERT INTO public.countries VALUES (642, 'RO', 'ROU', 'Romania', 'ro');
INSERT INTO public.countries VALUES (643, 'RU', 'RUS', 'Russian Federation', NULL);
INSERT INTO public.countries VALUES (646, 'RW', 'RWA', 'Rwanda', NULL);
INSERT INTO public.countries VALUES (654, 'SH', 'SHN', 'Saint Helena', NULL);
INSERT INTO public.countries VALUES (659, 'KN', 'KNA', 'Saint Kitts and Nevis', NULL);
INSERT INTO public.countries VALUES (662, 'LC', 'LCA', 'Saint Lucia', NULL);
INSERT INTO public.countries VALUES (666, 'PM', 'SPM', 'Saint Pierre and Miquelon', NULL);
INSERT INTO public.countries VALUES (670, 'VC', 'VCT', 'Saint Vincent and the Grenadines', NULL);
INSERT INTO public.countries VALUES (882, 'WS', 'WSM', 'Samoa', NULL);
INSERT INTO public.countries VALUES (674, 'SM', 'SMR', 'San Marino', NULL);
INSERT INTO public.countries VALUES (678, 'ST', 'STP', 'Sao Tome and Principe', NULL);
INSERT INTO public.countries VALUES (682, 'SA', 'SAU', 'Saudi Arabia', 'ar-SA');
INSERT INTO public.countries VALUES (686, 'SN', 'SEN', 'Senegal', NULL);
INSERT INTO public.countries VALUES (688, 'RS', 'SRB', 'Serbia', 'Cy-sr');
INSERT INTO public.countries VALUES (690, 'SC', 'SYC', 'Seychelles', NULL);
INSERT INTO public.countries VALUES (694, 'SL', 'SLE', 'Sierra Leone', NULL);
INSERT INTO public.countries VALUES (702, 'SG', 'SGP', 'Singapore', 'zh-SG');
INSERT INTO public.countries VALUES (703, 'SK', 'SVK', 'Slovakia', 'sk-SK');
INSERT INTO public.countries VALUES (705, 'SI', 'SVN', 'Slovenia', 'sl');
INSERT INTO public.countries VALUES (90, 'SB', 'SLB', 'Solomon Islands', NULL);
INSERT INTO public.countries VALUES (706, 'SO', 'SOM', 'Somalia', NULL);
INSERT INTO public.countries VALUES (710, 'ZA', 'ZAF', 'South Africa', 'af-ZA');
INSERT INTO public.countries VALUES (239, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', NULL);
INSERT INTO public.countries VALUES (724, 'ES', 'ESP', 'Spain', 'es-ES');
INSERT INTO public.countries VALUES (144, 'LK', 'LKA', 'Sri Lanka', NULL);
INSERT INTO public.countries VALUES (736, 'SD', 'SDN', 'Sudan', NULL);
INSERT INTO public.countries VALUES (740, 'SR', 'SUR', 'Suriname', NULL);
INSERT INTO public.countries VALUES (744, 'SJ', 'SJM', 'Svalbard and Jan Mayen', NULL);
INSERT INTO public.countries VALUES (748, 'SZ', 'SWZ', 'Swaziland', NULL);
INSERT INTO public.countries VALUES (752, 'SE', 'SWE', 'Sweden', 'sv-SE');
INSERT INTO public.countries VALUES (756, 'CH', 'CHE', 'Switzerland', 'de-CH');
INSERT INTO public.countries VALUES (760, 'SY', 'SYR', 'Syrian Arab Republic', NULL);
INSERT INTO public.countries VALUES (158, 'TW', 'TWN', 'Taiwan, Province of China', NULL);
INSERT INTO public.countries VALUES (762, 'TJ', 'TJK', 'Tajikistan', NULL);
INSERT INTO public.countries VALUES (834, 'TZ', 'TZA', 'Tanzania, United Republic of', NULL);
INSERT INTO public.countries VALUES (764, 'TH', 'THA', 'Thailand', 'th-TH');
INSERT INTO public.countries VALUES (626, 'TL', 'TLS', 'Timor-Leste', NULL);
INSERT INTO public.countries VALUES (768, 'TG', 'TGO', 'Togo', NULL);
INSERT INTO public.countries VALUES (772, 'TK', 'TKL', 'Tokelau', NULL);
INSERT INTO public.countries VALUES (776, 'TO', 'TON', 'Tonga', NULL);
INSERT INTO public.countries VALUES (50, 'BD', 'BGD', 'Bangladesh', NULL);
INSERT INTO public.countries VALUES (52, 'BB', 'BRB', 'Barbados', NULL);
INSERT INTO public.countries VALUES (112, 'BY', 'BLR', 'Belarus', 'be');
INSERT INTO public.countries VALUES (56, 'BE', 'BEL', 'Belgium', 'fr-BE');
INSERT INTO public.countries VALUES (84, 'BZ', 'BLZ', 'Belize', 'en-BZ');
INSERT INTO public.countries VALUES (204, 'BJ', 'BEN', 'Benin', NULL);
INSERT INTO public.countries VALUES (60, 'BM', 'BMU', 'Bermuda', NULL);
INSERT INTO public.countries VALUES (64, 'BT', 'BTN', 'Bhutan', NULL);
INSERT INTO public.countries VALUES (68, 'BO', 'BOL', 'Bolivia', 'es-BO');
INSERT INTO public.countries VALUES (70, 'BA', 'BIH', 'Bosnia and Herzegovina', NULL);
INSERT INTO public.countries VALUES (72, 'BW', 'BWA', 'Botswana', NULL);
INSERT INTO public.countries VALUES (74, 'BV', 'BVT', 'Bouvet Island', NULL);
INSERT INTO public.countries VALUES (76, 'BR', 'BRA', 'Brazil', 'pt-BR');
INSERT INTO public.countries VALUES (86, 'IO', 'IOT', 'British Indian Ocean Territory', NULL);
INSERT INTO public.countries VALUES (96, 'BN', 'BRN', 'Brunei Darussalam', NULL);
INSERT INTO public.countries VALUES (100, 'BG', 'BGR', 'Bulgaria', 'bg');
INSERT INTO public.countries VALUES (854, 'BF', 'BFA', 'Burkina Faso', NULL);
INSERT INTO public.countries VALUES (108, 'BI', 'BDI', 'Burundi', NULL);
INSERT INTO public.countries VALUES (116, 'KH', 'KHM', 'Cambodia', NULL);
INSERT INTO public.countries VALUES (120, 'CM', 'CMR', 'Cameroon', NULL);
INSERT INTO public.countries VALUES (132, 'CV', 'CPV', 'Cape Verde', NULL);
INSERT INTO public.countries VALUES (136, 'KY', 'CYM', 'Cayman Islands', NULL);
INSERT INTO public.countries VALUES (140, 'CF', 'CAF', 'Central African Republic', NULL);
INSERT INTO public.countries VALUES (148, 'TD', 'TCD', 'Chad', NULL);
INSERT INTO public.countries VALUES (152, 'CL', 'CHL', 'Chile', 'es-CL');
INSERT INTO public.countries VALUES (156, 'CN', 'CHN', 'China', 'zh-CN');
INSERT INTO public.countries VALUES (162, 'CX', 'CXR', 'Christmas Island', NULL);
INSERT INTO public.countries VALUES (170, 'CO', 'COL', 'Colombia', 'es-CO');
INSERT INTO public.countries VALUES (174, 'KM', 'COM', 'Comoros', NULL);
INSERT INTO public.countries VALUES (178, 'CG', 'COG', 'Congo', NULL);
INSERT INTO public.countries VALUES (180, 'CD', 'COD', 'Congo, the Democratic Republic of the', NULL);
INSERT INTO public.countries VALUES (184, 'CK', 'COK', 'Cook Islands', NULL);
INSERT INTO public.countries VALUES (188, 'CR', 'CRI', 'Costa Rica', 'es-CR');
INSERT INTO public.countries VALUES (384, 'CI', 'CIV', 'Cote D''Ivoire', NULL);
INSERT INTO public.countries VALUES (191, 'HR', 'HRV', 'Croatia', 'hr');
INSERT INTO public.countries VALUES (192, 'CU', 'CUB', 'Cuba', NULL);
INSERT INTO public.countries VALUES (196, 'CY', 'CYP', 'Cyprus', NULL);
INSERT INTO public.countries VALUES (203, 'CZ', 'CZE', 'Czech Republic', 'cs-CZ');
INSERT INTO public.countries VALUES (208, 'DK', 'DNK', 'Denmark', 'da-DK');
INSERT INTO public.countries VALUES (262, 'DJ', 'DJI', 'Djibouti', NULL);
INSERT INTO public.countries VALUES (212, 'DM', 'DMA', 'Dominica', 'es-DO');
INSERT INTO public.countries VALUES (214, 'DO', 'DOM', 'Dominican Republic', 'es-DO');
INSERT INTO public.countries VALUES (218, 'EC', 'ECU', 'Ecuador', 'es-EC');
INSERT INTO public.countries VALUES (818, 'EG', 'EGY', 'Egypt', 'ar-EG');
INSERT INTO public.countries VALUES (222, 'SV', 'SLV', 'El Salvador', 'es-SV');
INSERT INTO public.countries VALUES (226, 'GQ', 'GNQ', 'Equatorial Guinea', NULL);
INSERT INTO public.countries VALUES (232, 'ER', 'ERI', 'Eritrea', NULL);
INSERT INTO public.countries VALUES (233, 'EE', 'EST', 'Estonia', 'et');
INSERT INTO public.countries VALUES (231, 'ET', 'ETH', 'Ethiopia', NULL);
INSERT INTO public.countries VALUES (238, 'FK', 'FLK', 'Falkland Islands (Malvinas)', NULL);
INSERT INTO public.countries VALUES (234, 'FO', 'FRO', 'Faroe Islands', 'fo-FO');
INSERT INTO public.countries VALUES (242, 'FJ', 'FJI', 'Fiji', NULL);
INSERT INTO public.countries VALUES (246, 'FI', 'FIN', 'Finland', 'fi-FI');
INSERT INTO public.countries VALUES (250, 'FR', 'FRA', 'France', 'fr-FR');
INSERT INTO public.countries VALUES (254, 'GF', 'GUF', 'French Guiana', NULL);
INSERT INTO public.countries VALUES (258, 'PF', 'PYF', 'French Polynesia', NULL);
INSERT INTO public.countries VALUES (260, 'TF', 'ATF', 'French Southern Territories', NULL);
INSERT INTO public.countries VALUES (266, 'GA', 'GAB', 'Gabon', NULL);
INSERT INTO public.countries VALUES (270, 'GM', 'GMB', 'Gambia', NULL);
INSERT INTO public.countries VALUES (268, 'GE', 'GEO', 'Georgia', 'ka');
INSERT INTO public.countries VALUES (276, 'DE', 'DEU', 'Germany', 'de-DE');
INSERT INTO public.countries VALUES (288, 'GH', 'GHA', 'Ghana', NULL);
INSERT INTO public.countries VALUES (292, 'GI', 'GIB', 'Gibraltar', NULL);
INSERT INTO public.countries VALUES (300, 'GR', 'GRC', 'Greece', 'el-GR');
INSERT INTO public.countries VALUES (304, 'GL', 'GRL', 'Greenland', NULL);
INSERT INTO public.countries VALUES (308, 'GD', 'GRD', 'Grenada', NULL);
INSERT INTO public.countries VALUES (312, 'GP', 'GLP', 'Guadeloupe', NULL);
INSERT INTO public.countries VALUES (316, 'GU', 'GUM', 'Guam', NULL);
INSERT INTO public.countries VALUES (320, 'GT', 'GTM', 'Guatemala', 'es-GT');
INSERT INTO public.countries VALUES (324, 'GN', 'GIN', 'Guinea', NULL);
INSERT INTO public.countries VALUES (624, 'GW', 'GNB', 'Guinea-Bissau', NULL);
INSERT INTO public.countries VALUES (328, 'GY', 'GUY', 'Guyana', NULL);
INSERT INTO public.countries VALUES (332, 'HT', 'HTI', 'Haiti', NULL);
INSERT INTO public.countries VALUES (334, 'HM', 'HMD', 'Heard Island and Mcdonald Islands', NULL);
INSERT INTO public.countries VALUES (336, 'VA', 'VAT', 'Holy See (Vatican City State)', NULL);
INSERT INTO public.countries VALUES (340, 'HN', 'HND', 'Honduras', 'es-HN');
INSERT INTO public.countries VALUES (344, 'HK', 'HKG', 'Hong Kong', 'zh-HK');
INSERT INTO public.countries VALUES (348, 'HU', 'HUN', 'Hungary', 'hu-HU');
INSERT INTO public.countries VALUES (352, 'IS', 'ISL', 'Iceland', 'is');
INSERT INTO public.countries VALUES (356, 'IN', 'IND', 'India', 'gu-IN');
INSERT INTO public.countries VALUES (360, 'ID', 'IDN', 'Indonesia', 'id');
INSERT INTO public.countries VALUES (364, 'IR', 'IRN', 'Iran, Islamic Republic of', NULL);
INSERT INTO public.countries VALUES (368, 'IQ', 'IRQ', 'Iraq', 'ar-IQ');
INSERT INTO public.countries VALUES (372, 'IE', 'IRL', 'Ireland', 'en-IE');
INSERT INTO public.countries VALUES (376, 'IL', 'ISR', 'Israel', 'he-IL');
INSERT INTO public.countries VALUES (380, 'IT', 'ITA', 'Italy', 'it-IT');
INSERT INTO public.countries VALUES (388, 'JM', 'JAM', 'Jamaica', 'en-JM');
INSERT INTO public.countries VALUES (392, 'JP', 'JPN', 'Japan', 'ja');
INSERT INTO public.countries VALUES (400, 'JO', 'JOR', 'Jordan', 'ar-JO');
INSERT INTO public.countries VALUES (398, 'KZ', 'KAZ', 'Kazakhstan', 'kk-KZ');
INSERT INTO public.countries VALUES (404, 'KE', 'KEN', 'Kenya', 'sw-KE');
INSERT INTO public.countries VALUES (296, 'KI', 'KIR', 'Kiribati', NULL);
INSERT INTO public.countries VALUES (408, 'KP', 'PRK', 'Korea, Democratic People''s Republic of', NULL);
INSERT INTO public.countries VALUES (410, 'KR', 'KOR', 'Korea, Republic of', NULL);
INSERT INTO public.countries VALUES (414, 'KW', 'KWT', 'Kuwait', 'ar-KW');
INSERT INTO public.countries VALUES (417, 'KG', 'KGZ', 'Kyrgyzstan', NULL);
INSERT INTO public.countries VALUES (418, 'LA', 'LAO', 'Lao People''s Democratic Republic', NULL);
INSERT INTO public.countries VALUES (428, 'LV', 'LVA', 'Latvia', 'lv');
INSERT INTO public.countries VALUES (422, 'LB', 'LBN', 'Lebanon', 'ar-LB');
INSERT INTO public.countries VALUES (426, 'LS', 'LSO', 'Lesotho', NULL);
INSERT INTO public.countries VALUES (430, 'LR', 'LBR', 'Liberia', NULL);
INSERT INTO public.countries VALUES (434, 'LY', 'LBY', 'Libyan Arab Jamahiriya', NULL);
INSERT INTO public.countries VALUES (438, 'LI', 'LIE', 'Liechtenstein', 'de-LI');
INSERT INTO public.countries VALUES (440, 'LT', 'LTU', 'Lithuania', 'lt');
INSERT INTO public.countries VALUES (442, 'LU', 'LUX', 'Luxembourg', 'de-LU');
INSERT INTO public.countries VALUES (446, 'MO', 'MAC', 'Macao', NULL);
INSERT INTO public.countries VALUES (807, 'MK', 'MKD', 'North Macedonia', NULL);
INSERT INTO public.countries VALUES (450, 'MG', 'MDG', 'Madagascar', NULL);
INSERT INTO public.countries VALUES (454, 'MW', 'MWI', 'Malawi', NULL);
INSERT INTO public.countries VALUES (458, 'MY', 'MYS', 'Malaysia', 'ms-MY');
INSERT INTO public.countries VALUES (462, 'MV', 'MDV', 'Maldives', 'div-MV');
INSERT INTO public.countries VALUES (466, 'ML', 'MLI', 'Mali', NULL);
INSERT INTO public.countries VALUES (470, 'MT', 'MLT', 'Malta', NULL);
INSERT INTO public.countries VALUES (584, 'MH', 'MHL', 'Marshall Islands', NULL);
INSERT INTO public.countries VALUES (840, 'US', 'USA', 'United States', 'en-US');
INSERT INTO public.countries VALUES (124, 'CA', 'CAN', 'Canada', 'en-CA');
INSERT INTO public.countries VALUES (4, 'AF', 'AFG', 'Afghanistan', NULL);
INSERT INTO public.countries VALUES (8, 'AL', 'ALB', 'Albania', 'sq');
INSERT INTO public.countries VALUES (12, 'DZ', 'DZA', 'Algeria', 'ar-DZ');
INSERT INTO public.countries VALUES (16, 'AS', 'ASM', 'American Samoa', NULL);
INSERT INTO public.countries VALUES (20, 'AD', 'AND', 'Andorra', NULL);
INSERT INTO public.countries VALUES (24, 'AO', 'AGO', 'Angola', NULL);
INSERT INTO public.countries VALUES (660, 'AI', 'AIA', 'Anguilla', NULL);
INSERT INTO public.countries VALUES (10, 'AQ', 'ATA', 'Antarctica', NULL);
INSERT INTO public.countries VALUES (28, 'AG', 'ATG', 'Antigua and Barbuda', NULL);
INSERT INTO public.countries VALUES (32, 'AR', 'ARG', 'Argentina', 'es-AR');
INSERT INTO public.countries VALUES (51, 'AM', 'ARM', 'Armenia', 'hy');
INSERT INTO public.countries VALUES (533, 'AW', 'ABW', 'Aruba', NULL);
INSERT INTO public.countries VALUES (36, 'AU', 'AUS', 'Australia', 'en-AU');
INSERT INTO public.countries VALUES (40, 'AT', 'AUT', 'Austria', 'de-AT');
INSERT INTO public.countries VALUES (31, 'AZ', 'AZE', 'Azerbaijan', 'Cy-az-AZ');
INSERT INTO public.countries VALUES (44, 'BS', 'BHS', 'Bahamas', NULL);
INSERT INTO public.countries VALUES (48, 'BH', 'BHR', 'Bahrain', 'ar-BH');
INSERT INTO public.countries VALUES (780, 'TT', 'TTO', 'Trinidad and Tobago', 'en-TT');
INSERT INTO public.countries VALUES (788, 'TN', 'TUN', 'Tunisia', 'ar-TN');
INSERT INTO public.countries VALUES (792, 'TR', 'TUR', 'Turkey', 'tr-TR');
INSERT INTO public.countries VALUES (795, 'TM', 'TKM', 'Turkmenistan', NULL);
INSERT INTO public.countries VALUES (796, 'TC', 'TCA', 'Turks and Caicos Islands', NULL);
INSERT INTO public.countries VALUES (798, 'TV', 'TUV', 'Tuvalu', NULL);
INSERT INTO public.countries VALUES (800, 'UG', 'UGA', 'Uganda', NULL);
INSERT INTO public.countries VALUES (804, 'UA', 'UKR', 'Ukraine', 'uk-UA');
INSERT INTO public.countries VALUES (784, 'AE', 'ARE', 'United Arab Emirates', 'ar-AE');
INSERT INTO public.countries VALUES (826, 'GB', 'GBR', 'United Kingdom', 'en-GB');
INSERT INTO public.countries VALUES (581, 'UM', 'UMI', 'United States Minor Outlying Islands', NULL);
INSERT INTO public.countries VALUES (858, 'UY', 'URY', 'Uruguay', 'es-UY');
INSERT INTO public.countries VALUES (860, 'UZ', 'UZB', 'Uzbekistan', 'Cy-uz-UZ');
INSERT INTO public.countries VALUES (548, 'VU', 'VUT', 'Vanuatu', NULL);
INSERT INTO public.countries VALUES (862, 'VE', 'VEN', 'Venezuela', 'es-VE');
INSERT INTO public.countries VALUES (704, 'VN', 'VNM', 'Viet Nam', NULL);
INSERT INTO public.countries VALUES (92, 'VG', 'VGB', 'Virgin Islands, British', NULL);
INSERT INTO public.countries VALUES (850, 'VI', 'VIR', 'Virgin Islands, U.s.', NULL);
INSERT INTO public.countries VALUES (876, 'WF', 'WLF', 'Wallis and Futuna', NULL);
INSERT INTO public.countries VALUES (732, 'EH', 'ESH', 'Western Sahara', NULL);
INSERT INTO public.countries VALUES (887, 'YE', 'YEM', 'Yemen', 'ar-YE');
INSERT INTO public.countries VALUES (894, 'ZM', 'ZMB', 'Zambia', NULL);
INSERT INTO public.countries VALUES (716, 'ZW', 'ZWE', 'Zimbabwe', 'en-ZW');
INSERT INTO public.countries VALUES (499, 'ME', 'MNE', 'Montenegro', NULL);
INSERT INTO public.countries VALUES (0, 'XK', 'XKX', 'Kosovo', NULL);
INSERT INTO public.countries VALUES (248, 'AX', 'ALA', 'Aland Islands', NULL);
INSERT INTO public.countries VALUES (535, 'BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', NULL);
INSERT INTO public.countries VALUES (531, 'CW', 'CUW', 'Curacao', NULL);
INSERT INTO public.countries VALUES (831, 'GG', 'GGY', 'Guernsey', NULL);
INSERT INTO public.countries VALUES (833, 'IM', 'IMN', 'Isle of Man', NULL);
INSERT INTO public.countries VALUES (832, 'JE', 'JEY', 'Jersey', NULL);
INSERT INTO public.countries VALUES (652, 'BL', 'BLM', 'Saint Barthelemy', NULL);
INSERT INTO public.countries VALUES (663, 'MF', 'MAF', 'Saint Martin', NULL);
INSERT INTO public.countries VALUES (534, 'SX', 'SXM', 'Sint Maarten', NULL);
INSERT INTO public.countries VALUES (728, 'SS', 'SSD', 'South Sudan', NULL);
-- Data for Name: employee_status; Type: TABLE DATA; Schema: public; Owner: postgres
INSERT INTO public.employee_status OVERRIDING SYSTEM VALUE VALUES (1, 'Employed');
INSERT INTO public.employee_status OVERRIDING SYSTEM VALUE VALUES (2, 'Unemployed');
INSERT INTO public.employee_status OVERRIDING SYSTEM VALUE VALUES (3, 'Open to opportunity');
INSERT INTO public.employee_status OVERRIDING SYSTEM VALUE VALUES (5, 'Retired');
INSERT INTO public.employee_status OVERRIDING SYSTEM VALUE VALUES (6, 'Unemployable');
INSERT INTO public.employee_status OVERRIDING SYSTEM VALUE VALUES (4, 'Actively applying');
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
INSERT INTO public.users VALUES ('00000000-0000-0000-0000-000000000000', 'system', 'system', '{}', '{}', 'UTC', 'en-US', NULL, '2022-05-01 14:55:35.90698+02', '2022-07-09 10:54:32.545377+02');
END $pdd_data$
LANGUAGE plpgsql;
